window_size: 1000000
log_level: "info"
diff: 2000 
tuples_r: 5000000
tuples_s: 5000000
workers: 8
joiner_type: "handshake"
index_type: "bplustree"
stream_type: "random"
watcher_enabled: 0
watcher_interval: 10000
channel_buffer_size: 256
sosd_file: "../data/osm_cellids_200M_uint64"
sosd_shuffle: 1
preload: 1
