window_size: 100000
log_level: "off"
diff: 500
tuples_r: 500000
tuples_s: 500000
workers: 8
joiner_type: "handshake"
index_type: "alex"
stream_type: "sosd"
watcher_enabled: 0
watcher_interval: 10000
channel_buffer_size: 256
sosd_file: "../data/osm_cellids_200M_uint64"
sosd_shuffle: 1
preload: 1
